config/routes.rb
Rails.application.routes.draw do

  
  get  'todos' , to: 'todos#index'
  get 'todos/list', to: 'todos#list'
  get 'todos/new'
  post 'todos' , to: 'todos#create'
  get 'todos/:id', to: 'todos#show' , as: 'todo'
  get 'todos/:id/edit', to: 'todos#edit', as: 'edit_todo'
  patch 'todos/:id', to: 'todos#update'
  delete 'todos/:id' , to: 'todos#destroy'
  get 'todos/:id/complete', to: 'todos#complete', as: 'complete'
  
  
 
  
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todo.rb
class Todo < ApplicationRecord
    validates :description, presence: true
     validates :completed, inclusion: { in: [true, false] }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
    before_action :find_todo , only:[:show,:edit,:update,:destroy,:complete]
    
    def index
        @todos = Todo.all
        render :index
    end
   
    def new
        @todo = Todo.new
    end
    
    def create
     @todo = Todo.new(todo_params)
    
    @todo.save
        redirect_to todos_path
    end

    def show
     end

    def edit
    end

 def update
    @todo.update(todo_params)
    redirect_to todos_path
    end


    def destroy
        @todo.destroy
        redirect_to todos_path
  end

  def complete
    @todo.completed = true
    @todo.save
    redirect_to todos_path
  end
     
  def list
    @todos = Todo.all
    @completed = Todo.where(completed: true)
    @oncompleted = Todo.where(completed: false)
  end

  private
    def todo_params
        params.require(:todo).permit(:description, :completed)
    end
    
    def find_todo
        @todo = Todo.find(params[:id])
  end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TodoApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
 <%= render 'navbar', todo: @todo %>
    <%= yield %>
    
  </body>
</html>

app/views/todos/_form.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Formulario</title>
</head>
<body>
  <div class = "well">

    <%= form_with(model: todo,class:'form-horizontal' , local: true )do |form| %>
      
    
      <div class="form-group">
        <%= form.label :description,class:'col-sm-2 control-label'%>
        <div class="col-sm-6">
        <%= form.text_field :description, class:'form-control'%>
        </div>
    
        </div>
        
      <div  class="form-group">
        <%= form.label :completed,class:'col-sm-2 control-label'%>
        <div class="col-sm-6">
        <%= form.check_box :completed %>
        
        </div>
        
      </div>
    
      <div class="form-group">
       <div class="col-sm-offset-2 col-sm-10">
        <%= form.submit class:'btn btn-primary'%>
      </div>
      </div>
    <% end %>
    </div>
    
</body>
</html>

app/views/todos/_navbar.html.erb
 <!DOCTYPE html>
 <html lang="en">
 <head>
   <meta charset="UTF-8">
   <meta name="viewport" content="width=device-width, initial-scale=1.0">
   <meta http-equiv="X-UA-Compatible" content="ie=edge">
   <title>Document</title>
 </head>
 <body>
  <header>
    <nav class="navbar navbar-inverse">
      <div class="container-fluid">
        
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="<%=todos_path%>">Index</a>
        </div>
    
       
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">
            <li ><a href="<%=todos_list_url%>">List<span class="sr-only">(current)</span></a></li>
            <li> <a href="<%=todos_new_url%>">New ToDo</a></li>
  </header>
 </body>
 </html>

app/views/todos/edit.html.erb
<%= render 'form', todo: @todo %>

app/views/todos/index.html.erb
<div class="well">
<h1>  Lista de tareas</h1>

<table class= "table table-hover">
  <thead>
    <tr>
      <th>Description</th>
      <th>Completed</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody >
    <% @todos.each do |todo| %>
      <tr class ="info">
        <td ><%= todo.description %></td>
        <td><%= todo.completed %></td>

        <td><%= link_to 'Mostrar', todos_path, class: 'btn btn-info'%></td>
        <td><%= link_to 'Editar', edit_todo_path(todo),  class:'btn btn-warning'%></td>
        <td><%= link_to 'Borrar', todo, method: :delete, class: 'btn btn-danger'%></td>
     <td> <%= link_to 'completar', complete_path(todo), class: 'btn btn-primary'%></td>
 
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Crear ToDo', todos_new_path %>
</div>

app/views/todos/list.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>List</title>
</head>
<body >

  <div class= "well">
      <div class= "container">
          <div class= "row">
            
              <div class="col-md-6">
        
      
      
                  <table class="table table-hover">
                    <thead>
                      
                         <th><h1>Completados</h1></th>
                        <th colspan="3"></th>
                      
                    </thead>
                  
                    <tbody>
                      <% @completed.each do |todo| %>
                        
                         <tr > <td class="info"><%=todo.description%></td></tr>
                          
                      <% end %>
                    </tbody>
                  </table >
                  
                  <br>
                  
                  
                  
                    </div>
                    <div class="col-md-6">
                    
                  <table class="table table-hover">
                    <thead>
                      
                        <th> <h1>Incompletados</h1></th>
                        <th colspan="3"></th>
                      
                    </thead>
                  
                    <tbody>
                      <% @oncompleted.each do |todo| %>
                        
                         <tr > <td class="danger"><%=todo.description%></td></tr>
                          
                      <% end %>
                    </tbody>
                  </table>
                  
                  <br>
                  
                  
                  
                    </div>
      
      </div>
      </div>
  </div>
  
</body>
</html>

app/views/todos/new.html.erb
<%= render 'form', todo: @todo %>

app/views/todos/show.html.erb
<h1>Description: </h1>
<p>
  <%= @todo.description %>
</p>

<h2> Completed:</h2>
<p>
   <%=@todo.completed %>
</p>